name: picking-app-prod
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Which tag to use (provide full tag, eg. v1.0.0-rc.5)'
        required: true
  
jobs:
  test:
    name: Test APK prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.1'
    - name: create dotenv file
      run: printf SCANDIT_LICENSE_KEY=%s\\n ${{ secrets.SCANDIT_LICENSE_KEY }} > .env
    - name: analyze
      run: flutter analyze --no-fatal-infos

  build_and_deploy_prod_gooods:
    needs: [test]
    env:
      FLAVOR: prod_gooods
      TAG: ${{ github.event.inputs.tag }}
    name: Build APK prod_gooods
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.1'
    - name: create dotenv file
      run: printf SCANDIT_LICENSE_KEY=%s\\n ${{ secrets.SCANDIT_LICENSE_KEY }} > .env
    - name: Set RELEASE_VERSION env variable
      run: echo "RELEASE_VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: get packages
      run: flutter pub get
    - name: build
      run: flutter build apk --release --flavor $FLAVOR -t lib/main_$FLAVOR.dart --split-per-abi --build-name=$RELEASE_VERSION
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: gooods-picking-app-prod
        service_account_key: ${{ secrets.GCP_SA_KEY_GOODS_PROD }}
        export_default_credentials: true
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: 1:285917359767:android:fb44c81bcc2b4888de43d2
        groups: beta-testers
        releaseNotesFile: release_notes.txt
        file: build/app/outputs/flutter-apk/app-armeabi-v7a-${{ env.FLAVOR }}-release.apk

  build_and_deploy_stork_gooods:
    needs: [test]
    env:
      FLAVOR: prod
      TAG: ${{ github.event.inputs.tag }}
    name: Build APK prod stork
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.1'
    - name: create dotenv file
      run: printf SCANDIT_LICENSE_KEY=%s\\n ${{ secrets.SCANDIT_LICENSE_KEY }} > .env
    - name: Set RELEASE_VERSION env variable
      run: echo "RELEASE_VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: get packages
      run: flutter pub get
    - name: build
      run: flutter build apk --release --flavor $FLAVOR -t lib/main_$FLAVOR.dart --split-per-abi --build-name=$RELEASE_VERSION
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: gooods-picking-app-prod
        service_account_key: ${{ secrets.GCP_SA_KEY_STORK_PROD }}
        export_default_credentials: true
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: 1:130278022684:android:9970ef7149132c7a5309d9
        groups: beta-testers
        releaseNotesFile: release_notes.txt
        file: build/app/outputs/flutter-apk/app-armeabi-v7a-${{ env.FLAVOR }}-release.apk
